### ISSUE TITLE
OWM uses metric mm for rain regardless of requested units

### ISSUE THREAD

**Issue by PeteBa** [OpenSprinkler/OpenSprinkler-Weather#12] opened 2019-04-08 18:45 UTC
Hey Samer, I was looking at the OWM api spec and see that "rain" is always returned in metric mm regardless of the imperial units specified in the request. I confirmed this with a few api calls. This results in OS receiving mm but treating like inches. Obviously a big difference. Can you confirm this. Pete

**Comment by salbahra** [comment] 2019-04-08 19:21
You are absolutely correct this does seem to be an issue. We have had multiple reports of this however unfortunately I am out of the country (in Syria) and my network is extremely limited and I have not had a chance to look at this with the time needed to fix it. I will be back in the US this Friday and I am hoping to get this fixed by the weekend.

I apologize for this issue and will follow up once it's fixed.

Thanks for the feedback!

**Comment by PeteBa** [comment] 2019-04-08 20:34
No worries. It may just be me but I do wonder if "list.temp.day" is actually the average temperature in the middle of the day rather than the average temperature across the day. Looks like they have a set of morning, day, evening, night measurements which may be based on fixed segments of the day. I cant confirm this as I dont have access to that data stream but suggest checking as it would impact the zimmerman calc a fair bit. You might need to fallback on average of min and max.

**Comment by salbahra** [comment] 2019-04-09 22:32
You are absolutely correct as I just verified OWM always returns `mm` even though we have specified we want imperial units. I just added a quick conversion in the API code to return imperial which is what the app and firmware expect. Thanks for making this obvious!

Regarding the temperature issue, I will do as you suggest and average out the min/max instead of using the day temperature as I currently am.

Both of these changes have been pushed up and I will do some testing tomorrow and hopefully push this out soon.

**Comment by PeteBa** [comment] 2019-04-10 19:11
Had a quick look and suspect these commits will fix the OS zimmerman calc which expects `weather.temp` to be average for the day but will break the App weatherData call which expects `weather.temp` to be the current temperature.

You might want to split out the logic in **getOWMWeatherData()** as the two use cases are fairly different. I suspect the App weatherData response really needs two OWM api calls, the first, to the current api for actual current temperature, and secondly, a call to the forecast/daily api for the next few day's of forecasts.

**Comment by salbahra** [comment] 2019-04-10 19:14
That's what I am trying to avoid to be honest, they limit by number of API calls per some unit of time. I want to try to reduce our bill as much as possible. The way we had it before, was using `temp.day` which was also not the current temp either. So I think either way it's inaccurate. Let me think about this more, for now I have re-opened this issue.

**Comment by PeteBa** [comment] 2019-04-10 20:55
Hmm, this doesn't increase the api calls due to zimmerman but doubles them due to App refreshing the page. I dont know how close to the subscription limit you are nor whether doubling App based calls is significant compared with the constant volume of hourly zimmerman calls. I guess the obvious option would be to throttle api calls in App updateWeather() by caching data for say an hour. But this adds complexity ...

**Comment by salbahra** [comment] 2019-04-10 21:00
Ah I see what you mean! Separate the two methods so the app uses one and the firmware uses another. The firmware will use the current weather data whereas the app will use both: the current weather data and the forecast weather data.

The issue is the app will need both calls and that will 2x multiplier will get us much closer to our limits on the Startup plan we are currently on.

Caching was discussed between Ray and I but the complexity as you mentioned caused me to halt because I haven't had the time to properly implement that (in fact I removed the caching we used to have because maintaining and debugging it was becoming increasingly difficult for the humidity data).

I think as you said step one is separating the two methods so we can at least have the calls/endpoints we need and then figure out the caching.

Let me give this a little thought before I rush into it but please poke me if I haven't done anything in a few days.

Thank you!!

**Comment by PeteBa** [comment] 2019-04-10 21:15
So I think it would be easier to cache in App updateWeather() function rather than cache in weather server. App is client side so you dont need to worry about multi-user and stuff like mongodb.

Looking at App updateWeather(), I think you could just make the `weather` variable a global and also store `lastWeatherUpdated` as global too. That way you can just check if the data is stale and only then make the ajax call.

**Comment by salbahra** [comment] 2019-04-10 21:18
That's a great suggestion, but instead of a variable I could cache it in `localStorage` which would allow browser refreshes to also use the cached data when valid (as that's what worried me cmd + r or states where the data in memory would be lost like the app restarting). If we can make it to where the client doesn't try to poll it more than once every hour that should be a reasonable solution. Thank you for this idea!

**Comment by salbahra** [comment] 2019-04-29 00:02
I think with the recent changes merged in, we just need to update the app to cache the weather reply for an hour as we discussed. Since that's unrelated to the weather service. I will go ahead and close this again. Let me know if I have missed anything.

Thank you!

**Closed by salbahra** 2019-04-29 00:02 UTC
